# OmniEval/framework/base_model.py
from abc import ABC, abstractmethod
from typing import List, Any
import logging

class BaseOmniModel(ABC):
    """
    Abstract base class for Omni-modal Audio-Video Models.
    Users must inherit from this class and implement load_model() and generate().
    """
    def __init__(self, model_path: str, device_ids: List[int], **kwargs):
        """
        Initialize the model configuration.
        
        Args:
            model_path (str): Path to the model weights.
            device_ids (List[int]): List of allocated GPU IDs for this specific process.
                                    e.g., [0, 1] means this model instance can use cuda:0 and cuda:1.
        """
        self.model_path = model_path
        self.device_ids = device_ids
        self.logger = logging.getLogger(self.__class__.__name__)
        
        # Determine the primary device (usually the first one in the list)
        self.primary_device = f"cuda:{device_ids[0]}" if device_ids else "cpu"
        
        self.model = None
        self.processor = None
        self.load_model()

    @abstractmethod
    def load_model(self) -> None:
        """
        [Must Implement]
        Load the model weights, processors, or tokenizers here.
        Utilize self.device_ids to distribute the model across assigned GPUs if necessary 
        (e.g., for 30B/72B models using accelerate or vLLM).
        """
        pass

    @abstractmethod
    def generate(self, video_path: str, prompt: str, has_audio: bool) -> str:
        """
        [Must Implement]
        Define the single-sample inference logic.
        
        Args:
            video_path (str): Absolute path to the video file.
            prompt (str): The pre-formatted text prompt (Question + Options).
            has_audio (bool): Flag indicating if the video contains an audio track.
            
        Returns:
            str: The raw text string generated by the model.
        """
        pass