# OmniEval/framework/prompt_utils.py
import re
from typing import List, Optional

def build_multiple_choice_prompt(question: str, options: List[str]) -> str:
    """
    Constructs a standardized prompt for multiple choice questions.
    """
    options_text = "\n".join(options)
    prompt = (
        f"Question: {question}\n"
        f"Options:\n{options_text}\n\n"
        "Select the best answer from the options above. "
        "Directly provide the letter representing your choice and nothing else. "
        "Do not include the full text of the option, do not provide any explanation."
    )
    return prompt

def extract_choice_answer(response: str, valid_options: List[str] = ["A", "B", "C", "D", "E", "F"]) -> Optional[str]:
    """
    Extracts the selected option letter from the model's raw text response.
    Supports various output formats commonly generated by LLMs/MLLMs.
    """
    if not response:
        return None
        
    resp_upper = response.upper().strip()
    predicted_answer = None

    # Pattern 1: Starts strictly with the option letter (e.g., "A", "A.", "A)")
    for opt in valid_options:
        if resp_upper.startswith(opt) and (len(resp_upper) == 1 or resp_upper[1] in ['.', ')', ':', ' ', ',']):
            return opt

    # Pattern 2: Explicit declaration (e.g., "The answer is A", "Answer: A")
    answer_pattern = re.search(r'(?:THE\s+)?ANSWER\s*(?:IS|:)\s*([A-F])', resp_upper)
    if answer_pattern and answer_pattern.group(1) in valid_options:
        return answer_pattern.group(1)

    # Pattern 3: The option letter appears isolated in the text
    for opt in valid_options:
        if re.search(rf'\b{opt}\b', resp_upper):
            return opt

    # Pattern 4: Fallback - grab the very first valid alphabetical character
    for char in resp_upper:
        if char in valid_options:
            return char

    return None